name: Auto Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Connect Tailscale
        uses: tailscale/github-action@v2

        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master

        with:
          host: 100.87.75.117
          username: miguel
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd ~/ci-cd-lab

            git pull origin main

            docker stop devops-web || true
            docker rm devops-web || true

            docker build -t devops-web .

            docker run -d \
              --name devops-web \
              -p 8090:80 \
              devops-web
