nama: Auto Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master

        with:
          host: 172.16.130.142
          username: miguel
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script:
            cd ~/ci-cd-lab

            git pull origin main

            sudo docker stop devops-web || true
            sudo docker rm devops-web || true

            sudo docker build -t devops-web .

            sudo docker run -d \
              --name devops-web \
              -p 8090:80 \
              devops-web
